name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.23.0"

      - name: Install ui dependencies
        run: make deps-ui

      - name: Install go dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: make deps-go

      - name: Build
        run: make -j4 build

      - name: Test
        run: make -j4 test

      - name: Archive
        run: make archive

      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: "gift-goose-dist-archive"
          path: |
            gift-goose-dist.tar
